name: Cypress Testes

on: [push]

jobs: 
  cypress-etectron-tests:
    runs-on: ubuntu-lastest
    steps:
    - name: Get code 
      uses: actions/checkout@v4.2.2

      -name: Install dependecies 
       run: yarn install 

       -name: Run E2E tests
        run: yarn cypress run
  
    
